export const AREA_LOCATIONS = {
  STC: [
    'Novedades relevantes',
    'Bombas PD (Geho), centrífugas de carga y válvulas compresores',
    'Estanques y agitadores TK-020 / 021 PP007 ST-015 ST-500',
    'Estaanques TK-115 / 116 PP225/226/227',
    'Piscinas de emergencias',
    'Bombas de descarga TK-711',
  ],
  STR: [
    'Novedades reelevantes',
    'Harneros lineales y válvulas de dardo',
    'Bombas de impulsión de relaves y agua de sello STR 36"',
    "Válvulas STR 36\" y ZM's",
    'Estanques y Agitadores TK-002 / 003',
    'Estanque y Agitador TK-1004',
    'Válvulas STR 28"',
    'Bombas de impulsión de relaves y agua de sello STR 28"',
    'Cajón y bomba de recuperación de agua de rechazo harneros',
  ],
  Aguas: [
    'Área 410',
    'Estación Fija',
    'Dren Quillayes',
    'Choapa 1',
    'Choapa2',
    'Choapa 3',
    'Recirculación 2',
    'Acueducto',
    'Sentina Muro de cola',
    'Pozos 7 y 8 Cuncumen',
    'Cubeta',
    'Bocatomas',
    'Rios',
    'Otros',
    'Pozos ABQ.',
  ],
  'Espesadores 410': [
    'Novedades relevantes',
    'Espesadores de relave',
    'Válvulas de descarga espesadores',
    'Bombas de floculante',
    'Estanques de floculante y sistema de preparación',
    'Cajón distribuidor ST-077',
    'Bodega de floculante',
  ],
};

export const AREAS = ['STC', 'STR', 'Aguas', 'Espesadores 410'];
